package com.example.myapplication.data

data class Appointment(
    val id: String = "", // Will be generated by RTDB
    val doctorName: String = "",
    val date: String = "", // "MM/dd/yyyy"
    val time: String = "", // "hh:mm a"
    val type: String = "", // "Clinic" or "Video"
    val notes: String = "",
    val createdAt: Long = System.currentTimeMillis()
)